### ISSUE TITLE
Win 7 Border issue

### ISSUE THREAD

**Issue by Snow8** [corbindavenport/yosemite-chrome#1]
Hey,

i have an issue. The theme is awesome, but unfortunately it has an ugly blue border in win7 :( Could this be fixed? I checked out other themes that also "skin" the border accordingly.

![untitled](https://cloud.githubusercontent.com/assets/11486958/7920304/8869a4f4-089e-11e5-9cc3-b3353569def3.png)

Thank you!

**Comment by corbindavenport** [comment]
I can't find a way to change the color of the window border, can you link a theme that does it correctly? Maybe I can extract the code or something.

**Comment by Snow8** [comment]
https://chrome.google.com/webstore/detail/mac-os-theme/jkpadlfbbnobnjaeodjfnkogiigdmgff?utm_source=chrome-ntp-icon

**Comment by corbindavenport** [comment]
Fixed in Yosemite 1.1.

**Comment by Snow8** [comment]
Awesome. thank you! Just tried it and it looks sweet ;)
